"use client";
import { useState } from "react";
import type { Order } from "@/src/types/order";
import { formatToman } from "@/src/lib/money";

const labels = { pending_payment: "در انتظار پرداخت", paid: "پرداخت‌شده", processing: "در حال آماده‌سازی", shipped: "ارسال‌شده", delivered: "تحویل‌شده", cancelled: "لغوشده", payment_failed: "پرداخت ناموفق" } as const;
export default function TrackOrderPage() {
  const [order, setOrder] = useState<Order | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(""); setOrder(null); const data = new FormData(event.currentTarget); const response = await fetch(`/api/orders/track?trackingCode=${encodeURIComponent(String(data.get("trackingCode")))}&mobile=${encodeURIComponent(String(data.get("mobile")))}`); const result = await response.json().catch(() => null); setLoading(false); if (response.ok) setOrder(result); else setError(result?.message || "سفارش پیدا نشد."); }
  return <main className="mx-auto min-h-[65vh] max-w-3xl px-4 py-12"><section className="rounded-3xl border bg-white p-6 sm:p-8"><h1 className="text-3xl font-black">پیگیری سفارش</h1><p className="mt-2 text-slate-500">کد سفارش و شماره موبایل ثبت‌شده را وارد کنید.</p><form onSubmit={submit} className="mt-6 grid gap-3 sm:grid-cols-[1fr_1fr_auto]"><input required name="trackingCode" placeholder="کد سفارش" className="rounded-xl border px-4 py-3"/><input required name="mobile" placeholder="شماره موبایل" className="rounded-xl border px-4 py-3"/><button disabled={loading} className="rounded-xl bg-red-600 px-6 font-bold text-white">پیگیری</button></form>{error && <p className="mt-5 rounded-xl bg-red-50 p-3 text-red-600">{error}</p>}{order && <div className="mt-8 rounded-2xl bg-slate-50 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><span className="text-sm text-slate-500">سفارش</span><strong className="mr-2">{order.trackingCode}</strong></div><span className="rounded-full bg-red-100 px-4 py-2 text-sm font-bold text-red-700">{labels[order.status]}</span></div><div className="mt-5 space-y-2 border-t pt-4">{order.items.map((item) => <div key={item.productId} className="flex justify-between gap-4"><span>{item.title} × {item.quantity.toLocaleString("fa-IR")}</span><span>{formatToman(item.unitPrice * item.quantity)}</span></div>)}</div><div className="mt-4 flex justify-between border-t pt-4 font-black"><span>مبلغ کل</span><span>{formatToman(order.total)}</span></div>{order.paymentReference && <p className="mt-3 text-sm text-slate-500">شماره مرجع پرداخت: {order.paymentReference}</p>}</div>}</section></main>;
}
