"use client";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { MessageCircle, Trash2 } from "lucide-react";

type Status = "new" | "contacted" | "quoted" | "completed" | "cancelled";
interface Inquiry { id: number; name: string; mobile: string; productTitle: string; quantity?: number; description?: string; preferredContact?: string; status: Status; adminNote: string; createdAt: string }
const labels: Record<Status, string> = { new: "جدید", contacted: "تماس گرفته شد", quoted: "پیشنهاد ارسال شد", completed: "تکمیل‌شده", cancelled: "لغوشده" };

async function parse(response: Response) { if (response.status === 204) return null; const body = await response.json(); if (!response.ok) throw new Error(body.message || "عملیات ناموفق بود"); return body; }
export default function InquiriesPage() {
  const client = useQueryClient();
  const { data = [], isLoading, isError } = useQuery<Inquiry[]>({ queryKey: ["admin", "inquiries"], queryFn: () => fetch("/api/admin/inquiries").then(parse) });
  async function update(id: number, patch: Partial<Pick<Inquiry, "status" | "adminNote">>) { await parse(await fetch(`/api/admin/inquiries/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(patch) })); client.invalidateQueries({ queryKey: ["admin", "inquiries"] }); }
  async function remove(id: number) { if (!confirm("این درخواست حذف شود؟")) return; await parse(await fetch(`/api/admin/inquiries/${id}`, { method: "DELETE" })); client.invalidateQueries({ queryKey: ["admin", "inquiries"] }); }
  return <div dir="rtl" className="space-y-6"><div><h1 className="flex items-center gap-3 text-3xl font-black"><MessageCircle className="text-red-500" />درخواست‌های تماس</h1><p className="mt-2 text-slate-500">پیگیری استعلام‌ها و درخواست‌های ثبت‌شده مشتریان</p></div>{isLoading && <div className="rounded-2xl border bg-white p-10 text-center">در حال دریافت...</div>}{isError && <div className="rounded-2xl bg-red-50 p-5 text-red-600">دریافت درخواست‌ها ناموفق بود.</div>}{!isLoading && !data.length && <div className="rounded-2xl border bg-white p-10 text-center text-slate-500">هنوز درخواستی ثبت نشده است.</div>}<div className="grid gap-4">{data.map((item) => <article key={item.id} className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex flex-col justify-between gap-4 lg:flex-row"><div><div className="flex flex-wrap items-center gap-3"><h2 className="text-lg font-black">{item.name}</h2><span className="rounded-full bg-slate-100 px-3 py-1 text-xs">{labels[item.status]}</span></div><a href={`tel:${item.mobile}`} dir="ltr" className="mt-2 inline-block text-red-600">{item.mobile}</a><p className="mt-3 font-semibold">{item.productTitle}{item.quantity ? ` — تعداد ${item.quantity}` : ""}</p>{item.description && <p className="mt-2 text-sm text-slate-500">{item.description}</p>}<p className="mt-3 text-xs text-slate-400">{new Date(item.createdAt).toLocaleString("fa-IR")}</p></div><div className="flex min-w-72 flex-col gap-3"><select value={item.status} onChange={(event) => update(item.id, { status: event.target.value as Status })} className="min-h-11 rounded-xl border px-3">{Object.entries(labels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><textarea defaultValue={item.adminNote} onBlur={(event) => { if (event.target.value !== item.adminNote) update(item.id, { adminNote: event.target.value }); }} placeholder="یادداشت مدیر" className="min-h-20 rounded-xl border p-3 text-sm" /><button onClick={() => remove(item.id)} className="flex min-h-10 items-center justify-center gap-2 rounded-xl bg-red-50 text-sm font-bold text-red-600"><Trash2 size={16} />حذف درخواست</button></div></div></article>)}</div></div>;
}
