"use client";
import { useState, type FormEvent } from "react";
import { CheckCircle2, Send } from "lucide-react";

export default function InquiryRequestForm({ productId, productTitle }: { productId?: number; productTitle: string }) {
  const [loading, setLoading] = useState(false); const [success, setSuccess] = useState(false); const [error, setError] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(""); const form = new FormData(event.currentTarget); try { const response = await fetch("/api/inquiries", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: String(form.get("name")), mobile: String(form.get("mobile")), productId, productTitle, quantity: Number(form.get("quantity")) || 1, description: String(form.get("description") || ""), preferredContact: String(form.get("preferredContact")) }) }); const body = await response.json(); if (!response.ok) throw new Error(body.message); setSuccess(true); event.currentTarget.reset(); } catch (caught) { setError(caught instanceof Error ? caught.message : "ثبت درخواست ناموفق بود"); } finally { setLoading(false); } }
  if (success) return <div className="rounded-2xl bg-emerald-50 p-5 text-center text-emerald-700"><CheckCircle2 className="mx-auto mb-2" /><b>درخواست شما ثبت شد</b><p className="mt-1 text-sm">کارشناسان در اولین فرصت تماس می‌گیرند.</p></div>;
  return <form onSubmit={submit} className="space-y-3"><div className="grid gap-3 sm:grid-cols-2"><input required name="name" placeholder="نام و نام خانوادگی" className="min-h-12 rounded-xl border bg-slate-50 px-4 outline-none focus:border-red-400" /><input required name="mobile" inputMode="tel" pattern="09[0-9]{9}" placeholder="شماره موبایل" dir="ltr" className="min-h-12 rounded-xl border bg-slate-50 px-4 text-right outline-none focus:border-red-400" /><input name="quantity" type="number" min="1" defaultValue="1" placeholder="تعداد" className="min-h-12 rounded-xl border bg-slate-50 px-4 outline-none focus:border-red-400" /><select name="preferredContact" className="min-h-12 rounded-xl border bg-slate-50 px-4 outline-none"><option value="phone">تماس تلفنی</option><option value="whatsapp">واتساپ</option></select></div><textarea name="description" placeholder="توضیحات اختیاری" className="min-h-20 w-full rounded-xl border bg-slate-50 p-4 outline-none focus:border-red-400" />{error && <p className="rounded-xl bg-red-50 p-3 text-sm text-red-600">{error}</p>}<button disabled={loading} className="flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-slate-900 font-bold text-white disabled:opacity-50"><Send size={17} />{loading ? "در حال ثبت..." : "ثبت درخواست تماس"}</button></form>;
}
